name: prevent-file-change

on:
<<<<<<< HEAD
  pull_request:
=======
  pull_request_target:
>>>>>>> upstream/master
permissions: {}

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prevent file change
<<<<<<< HEAD
        uses: xalvarez/prevent-file-change-action@004d9f17c2e4a7afa037cda5f38dc55a5e9c9c06 # v1.9.1
=======
        uses: xalvarez/prevent-file-change-action@dbc67c205c9ed02aa39c497b422c24f364c3e8dd # v3.0.1
>>>>>>> upstream/master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Regex, /src/lang/*.json is not allowed to be changed, except for /src/lang/en.json
          pattern: '^(?!src/lang/en\.json$)src/lang/.*\.json$'
          trustedAuthors: UptimeKumaBot
